### ISSUE TITLE
Usernames with spaces

### ISSUE THREAD

**Issue by knttr** [bpcurse/nextcloud-userexport#21]
Thank you very much for this script - it gives us a better overview than the screen shots used to date...

Usernames with spaces are not listed in the table / CSV-file

The Nextcloud Documentation states:
> Login names may contain letters (a-z, A-Z), numbers (0-9), dashes (-), underscores (_), periods (.) and at signs (@). After creating the user, you may fill in their Full Name if it is different than the login name, or leave it for the user to complete.

Unfortunately the User frontend allows usernames with spaces and we're stuck with these usernames.

Can the script be updated to include usernames with spaces?

**Comment by bpcurse** [comment]
@knttr Thank you for your feedback!
Interesting case, I will check later today if the issue is in the API response or in the script.

**Comment by bpcurse** [comment]
Could you please provide the following additional information: 

- Nextcloud server version
- Browser you are using to access the script (on Win/Linux/Mac)
- An anonymized example how your usernames are built (e.g. "a test", "mike the boss", ...)

Thank you!

**Comment by bpcurse** [comment]
@knttr The additional info isn't necessary any more. I could not reproduce the issue on Nextcloud 17 but I could on Nextcloud 16.

As of Nextcloud 17 the API seems to handle some improper encoding in URLs. In Nextcloud 16 it does not.

The script now encodes spaces in login IDs used for API calls properly as "%20".
I have pushed a commit to master that fixes this issue and will release v0.3.1.

Feel free to reopen or file another issue if this doesn't solve the problem for you.

**Comment by knttr** [comment]
Thank you for the very fast response.

I can confirm that issue is resolved with the release v0.3.1.
(We are using Nextcloud 17.0.2)
