### ISSUE TITLE
force https when no no protocol is specified

### ISSUE THREAD

**Issue by David100mark** [bpcurse/nextcloud-userexport#38]
force https when no no protocol is specified for server adress

**Comment by bpcurse** [comment]
In the next version `https://` will be prepended if no protocol has been specified, instead of throwing an error.

**Comment by bpcurse** [comment]
Done in https://github.com/bpcurse/nextcloud-userexport/commit/dcf0f187e3f5003b8d8c062ba32b4a402a56db1b
